In [1]:
import numpy as np
import pandas as pd
import nnfs
from nnfs.datasets import spiral_data



In [2]:
inputs = [1, 2, 3, 2.5]


weights = [[0.2, 0.8, -0.5, 1.0], 
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
# inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
# inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]

layer_outputs = []

# for neuron_weight, neuron_bias in zip(weights, biases):
#     # print(neuron_weight, neuron_bias)
#     neuron_output = 0
#     for n_input, weight in zip(inputs, neuron_weight):
#         print(n_input, weight)
#         neuron_output += n_input* weight
#     neuron_output += neuron_bias
#     layer_outputs.append(neuron_output)
# print(layer_outputs)

hard code in for loop

In [3]:
inputs = [1, 2, 3, 2.5]


weights = [[0.2, 0.8, -0.5, 1.0], 
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

layer_outputs = []

# for i in range(len(weights)):
#     neuron_weight = weights[i]
#     neuron_bias = biases[i]

#     neuron_output = 0
#     for j in range(len(neuron_weight)):
#         neuron_output += inputs[j] * neuron_weight[j]
    
#     neuron_output += neuron_bias
#     layer_outputs.append(neuron_output)
# print(layer_outputs)





In [4]:
output = np.dot(weights, inputs) + biases

In [5]:
output

array([4.8  , 1.21 , 2.385])

Using numpy

In [6]:
inputs2 = [[1, 2, 3, 2.5],
           [2.0, 5.0, -1.0, 2.0],
           [-1.5, 2.7, 3.3, -0.8]]


weights2 = [[0.2, 0.8, -0.5, 1.0], 
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases2 = [2, 3, 0.5]

weights3 = [[0.1, -0.14, 0.5], 
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases3 = [-1, 2, -0.5]

In [7]:
layer1_output = np.dot(inputs2, np.array(weights2).T) + biases2
layer1_output 

array([[ 4.8  ,  1.21 ,  2.385],
       [ 8.9  , -1.81 ,  0.2  ],
       [ 1.41 ,  1.051,  0.026]])

In [8]:
layer2_output = np.dot(layer1_output, np.array(weights3).T) + biases3


In [9]:
layer2_output

array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])

In [10]:
X = [[1, 2, 3, 2.5],
    [2.0, 5.0, -1.0, 2.0],
    [-1.5, 2.7, 3.3, -0.8]]



In [ ]:
np.random.seed(0)

class Layer_dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons) #just so we don't have to transpose
        self.biases = np.zeros((1, n_neurons))

    def forward(self, inputs):
        self.output = np.dot(inputs,  self.weights) + self.biases

class Activation_ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

class Activation_softmax:
    def forward(self, inputs):
        exp_values = np.exp(inputs - np.max(inputs, axis = 1, keepdims = True))
        probabilities = exp_values / np.sum(exp_values, axis = 1, keepdims = True)
        self.output = probabilities

class Loss:
    def calculate(self, output, y):
        sample_losses = self.forward(output, y)
        data_loss = np.mean(sample_losses)
        return data_loss

class Loss_CatergoricalCrossEnropy(Loss):
    def forward(self, y_pred, y_true):
        samples = len(y_pred)
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)

        if len(y_true.shape) == 1:
            correct_confidences = y_pred_clipped[range(samples),y_true]
        elif len(y_true.shape) == 2: #2D
            correct_confidences = np.sum(y_pred_clipped * y_true, axis = 1)
        negative_log_likelihoods = -np.log(correct_confidences)
        return negative_log_likelihoods
    

        


In [56]:
x, y = spiral_data(samples=100, classes=3)

dense1 = Layer_dense(2, 3)
activation1 = Activation_ReLU()

dense2 = Layer_dense(3, 3)
activation2 = Activation_softmax()

dense1.forward(x)
activation1.forward(dense1.output)

dense2.forward(activation1.output)
activation2.forward(dense2.output)

# print(activation2.output[:5])
Loss_function = Loss_CatergoricalCrossEnropy()
loss  = Loss_function.calculate(activation2.output, y)
print("Loss", loss)



Loss 1.0986104615465142


In [13]:
layer1 = Layer_dense(2, 5)
layer2 = Layer_dense(5, 2)
activation1 = Activation_ReLU()

layer1.forward(x)
# print(layer1.output)

activation1.forward(layer1.output)
# print(activation1.output)
layer1.weights.shape


(2, 5)

In [14]:
# layer1.forward(X)
# layer1.output

In [15]:
layer2.forward(layer1.output)
layer2.output

array([[ 0.00000000e+00,  0.00000000e+00],
       [ 9.81882682e-05,  3.17570964e-04],
       [ 1.42717883e-04,  5.15408756e-04],
       [-1.04642949e-05,  1.57348631e-04],
       [ 2.39604437e-05,  3.20992864e-04],
       [ 5.42950592e-04,  1.65675689e-03],
       [ 2.03148767e-04,  9.55478037e-04],
       [ 5.34132100e-04,  1.88810991e-03],
       [ 5.25634859e-04,  1.94889917e-03],
       [ 2.72989295e-04,  1.34539071e-03],
       [ 3.37508273e-04,  1.58950452e-03],
       [-5.25551606e-04, -9.22283145e-04],
       [-2.64781310e-04, -4.05835014e-05],
       [ 2.58886034e-05,  8.91495869e-04],
       [-3.74557018e-04, -2.48713207e-04],
       [-4.74840180e-04, -4.94005087e-04],
       [-1.46219072e-03, -3.73145657e-03],
       [-4.15494128e-04, -1.81122387e-04],
       [-1.09651470e-03, -2.28017702e-03],
       [-2.10351459e-04,  5.67667296e-04],
       [ 1.33672131e-03,  4.92918889e-03],
       [-2.02335064e-03, -5.29870251e-03],
       [-2.32042090e-03, -6.40163919e-03],
       [-1.

In [16]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
result = []

for i in inputs:
    result.append(max(i, 0))


In [17]:
result

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]

Softmax Activation 

In [53]:
layer_outputss = np.array([[4.8, 1.21, 2.385],
                  [0.9, -1.81, 0.2],
                  [1.41, 1.051, 0.26]])

len(layer_outputss)

3

In [19]:
layer_outputss = layer_outputss - np.max(layer_outputss)
exp = np.exp(layer_outputss)


exp = exp / np.sum(layer_outputss, axis=1, keepdims=True)
exp



array([[-1.66527893e-01, -4.59589183e-03, -1.48821547e-02],
       [-1.33963676e-03, -8.91351522e-05, -6.65243928e-04],
       [-2.88626397e-03, -2.01569273e-03, -9.13897299e-04]])

In [27]:
softmax_outputs = np.array([[0.7, 0.1, 0.2],
                    [0.1, 0.5, 0.4],
                    [0.02, 0.9, 0.08]])

class_targets = [0, 1, 1]

In [48]:
neg_log = -np.log(softmax_outputs[range(len(softmax_outputs)), class_targets])
neg_log

array([0.35667494, 0.69314718, 0.10536052])

In [45]:
average_loss = np.mean(neg_log)
average_loss

np.float64(0.38506088005216804)

C:\Users\ZAK-TECH\AppData\Local\Temp\ipykernel_21864\2869289095.py:1: RuntimeWarning: divide by zero encountered in log
  -np.log(0)


np.float64(inf)